[project]
name = "mlweather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "julien-kap", email = "jgooris@kap.bzh" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "polars>=1.30.0",
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
