[project]
name = "mlweather"
version = "0.2.0"
description = "A package to collect and prepare weather data easily, massively and at blazzing speed for ml jobs - based on the Open-Meteo weather source"
readme = "README.md"
authors = [
    { name = "Julien Gooris", email = "jgooris@kap.bzh" }
]
requires-python = ">=3.12"
dependencies = [
    "geopy>=2.4.1",
    "polars>=1.30.0",
    "pytest>=8.4.0",
    "pytest-cov>=6.1.1",
    "requests>=2.32.3",
    "requests-cache>=1.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "mypy>=1.19.1",
    "pyarrow>=22.0.0",
    "pytest>=8.4.0",
    "python-dotenv>=1.1.0",
    "xlsxwriter>=3.2.9",
]
