name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Python with uv
        run: |
          uv python install 3.12
          uv sync

      - name: Run Ruff
        run: uv run ruff check .
